#!/bin/bash
set -ex

SCRIPTPATH=$( cd "$(dirname "$0")" ; pwd -P )

# Compute the number of warnings generated by xcpretty
warning_number_space=$(cat ${logFile} | grep -o "⚠️.*" | sort | uniq | wc -l)

# Trim all spaces
warning_number="$(echo -e "${warning_number_space}" | tr -d '[:space:]')"

# Test regression
$SCRIPTPATH/relapse "warning_relapse" "$warning_number" "<" ".ci/ci.sqlite3"

# update saved database
git add .ci/ci.sqlite3
git commit -am "Update Test Count database"
git push origin
